timezone: "America/Los_Angeles"

max_past_weeks: 0

toggl:
  work_projects:
    - "1. Work"
    - "2. Learning"
    - "3. Outer"
  unendorsed_project: "6. Sins"
  sleep_project: "5. Upkeep"
  sleep_description: "Sleep"
  all_projects:
    - "1. Work"
    - "2. Learning"
    - "3. Outer"
    - "4. Rest"
    - "5. Upkeep"
    - "6. Sins"

todoist:
  morning_tasks:
    - "Morning Hygiene"
    - "Morning OODA"
  evening_tasks:
    - "Night Hygiene"
    - "Night OODA"
  virtue_tasks:
    - "Fortitude"

google_sheets:
  form_responses_sheet: "Form Responses 1"
